### ISSUE TITLE
Better executable name

### ISSUE THREAD

**Issue by pengwynn** [pengwynn/octonaut#1]
I will end up aliasing to `o`, but such a short executable is a bit presumptious.

Need to pick one of:
- `octonaut`
- `octo`
- `naut`
- `ocat`

or...

**Comment by bernardobarreto** [comment]
I like "octo" :+1:

**Comment by sarahhodne** [comment]
I was considering aliasing this as `octo` before realising I could just do `o`, so :+1: for `octo`.

**Comment by pengwynn** [comment]
Since there's an [octo gem that uses `octo`](https://github.com/nanzhong/octo/tree/master/bin), I think we'll use `octonaut` for now and update the README with alias, completion instructions when shell completion is ready.
