### ISSUE TITLE
Unable to run octonaut -- "no such file to load -- json (LoadError)" error

### ISSUE THREAD

**Issue by izuzak** [pengwynn/octonaut#14]
I'm completely new to OSX and Ruby so I'm probably just making a rookie mistake... But I'm having problems with running octonaut.

The octonaut installation and execution outputs are in [this gist](https://gist.github.com/izuzak/a393be9f625c0f14a835), as well as the ruby, gem and osx versions.

Thanks!

**Comment by pengwynn** [comment]
Thanks so much for reporting. I'm still on the fence for supporting 1.8.7 with this (newish) gem. I'd recommend upgrading to Ruby 1.9.3: http://www.ruby-lang.org/en/downloads/

**Comment by izuzak** [comment]
That fixes it! Updated to `ruby 2.0.0p0` and had to get around the [SSL problems](http://railsapps.github.com/openssl-certificate-verify-failed.html), but now everything is working nicely. Cheers!
